### ISSUE TITLE
Mass addition of phonemes (Perhaps an import function?)

### ISSUE THREAD

**Issue by Matalya** [terahlunah/monke#2]
Hi! First of all, I _adore_ this tool. It looks so comprehensive.

I wanted to propose a feature for the addition of phonemes as terminals more than one at a time. I have a grand total of 91 unique sounds I have to pass over which isn't undoable, but certainly a tool with this much polish and thoroughness would have a way to mass import some stuff in a compatible format.

Additionally (Or alternatively), a QoL feature you could add, Idk if it's even doable, is to place the cursor automatically on the text field of a terminal when you create it.

That's all. Thanks for reading **and** for Monke!

Mmmmmmmonkeee~

**Comment by terahlunah** [comment]
Hi Matalya, thanks for the kind words!

I'm not sure I understand your needs, could you describe a bit more your use case?

**Comment by terahlunah** [comment]
Ok I think I understand better.

One thing you could do right now is to use regular rules instead of terminal rules (which are just a nicer way to write a terminal only regular rule).
For example if you have the terminals: a, b, c, d, e, f, g, h, ...
You can create a regular rule "Terminal" with a single expression containing all your terminals like that:
```'a'/'b'/'c'/'d'/'e'/'f'/'g'/'h'/...```
which is easier to generate automatically.

Would that cover your need? 

---

The `Import Config` button is the mirror of the `Export Config` button, but this is mainly for backup/saving/sharing your work in a file format, not really intended for manual edition.

**Comment by Matalya** [comment]
Huh! That's… that might work actually, yeah. Maybe there might be some differences based on how the system picks terminals vs how it picks choices, but for now it should be ok. Thanks!

**Comment by terahlunah** [comment]
> Maybe there might be some differences based on how the system picks terminals vs how it picks choices

It's strictly equivalent, terminal rules are internally converted to regular rule with choices.

**Comment by terahlunah** [comment]
I'm gonna close the issue for now
