### ISSUE TITLE
Rewrites and exclusions does not recognize certain characters.

### ISSUE THREAD

**Issue by ThiagokawanoGithub** [terahlunah/monke#6]
I was trying to make a conlang, and it uses non-english letters for its romanization, such as Š, Č, Ř, etc. Unfortunately, when I try to add rules to them the site says they are unexpected characters and there seems to be no workaround.

![chrome_screenshot_30 de jul  de 2024 08_12_25 BRT](https://github.com/user-attachments/assets/fb974baf-25b3-4f60-be0e-24be9f5172a9)

**Comment by terahlunah** [comment]
I'll have a look asap

**Comment by terahlunah** [comment]
I think it's because you forgot the apostrophes around your letters/clusters.
`ši` should be `'ši'` for example.

You need to use apostrophes around raw letters in your rules (so the engine can distinguish between letters and rules). The only exception is in the Terminal rules, where the apostrophes are implied since they represent single letters.

**Comment by ThiagokawanoGithub** [comment]
Thanks.
