### ISSUE TITLE
[Feature request] Warning popup/ prompt before "Clear"

### ISSUE THREAD

**Issue by pickaxe828** [terahlunah/monke#7]
Please add a warning popup/ prompt before actually executing "Clear".
I have accidentally clicked the button and now my word gen is gone 🥲

**Comment by terahlunah** [comment]
Sorry to hear that, I just made it so that every config change will create a new entry in your browser's history (in https://github.com/terahlunah/monke/commit/1941665414113545906d6fe17c2cd3ee3d348fbf). That way you can "undo" any mistakes by hitting the "back" button.

Hopefully that should protect people from losing their work in the future.
